export const FETCH_MATCHES_REQUEST = "FETCH_MATCHES_REQUEST";
export const FETCH_MATCHES_SUCCESS = "FETCH_MATCHES_SUCCESS";
export const FETCH_MATCHES_FAIL = "FETCH_MATCHES_FAIL";

export const FETCH_FINISHED_MATCHES_REQUEST = "FETCH_FINISHED_MATCHES_REQUEST";
export const FETCH_FINISHED_MATCHES_SUCCESS = "FETCH_FINISHED_MATCHES_SUCCESS";
export const FETCH_FINISHED_MATCHES_FAIL = "FETCH_FINISHED_MATCHES_FAIL";

export const FILTER_MATCHES_REQUEST = "FILTER_MATCHES_REQUEST";
export const FILTER_MATCHES_SUCCESS = "FILTER_MATCHES_SUCCESS";
export const FILTER_MATCHES_FAIL = "FILTER_MATCHES_FAIL";

export const CLEAR_MATCHES = "CLEAR_MATCHES";
